name: Aliyun Signin
on:
  schedule:
  -cron:'20 18 * * *'
  workflow_dispatch:
jobs:
  signin:
    name: Aliyun Signin
    runs-on:ubuntu-lateststeps:
    - uses: ImYrS/aliyun-auto-signin@main
    with:
      REFRESH_TOKENS: ${{ secrets.REFRESH_TOKENS }}
      GP_TOKEN: ${{ secrets.GP_TOKEN }}
      PUSH TYPES:'TELEGRAM'
      TELEGRAM BOT_TOKEN:${{ secrets. TELEGRAM_BOT_TOKEN H }}
      TELEGRAM_CHAT_ID: $i{ secrets.TELEGRAM_CHAT_ID }}
